spring:
  application:
    name: flowfix-assistant
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  jackson:
    default-property-inclusion: non_null

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
